
import { StandardButton, LineEdit, Button, TextEdit } from "std-widgets.slint";
export component OpenDialog inherits Dialog {
    title: "Open File";
    in-out property <string> path;
    callback open_file();
    Rectangle {
    HorizontalLayout {Text {text:"Path/URL";}
    LineEdit {text <=> path;}
    Button {text: "...";
    clicked => {open_file();}}
    }
    }

    StandardButton {kind:ok;}
    StandardButton {kind:cancel;}

}